[profile.default]
solc = '0.8.22'
verbosity = 3
src = "contracts"
test = "test"
out = "artifacts"
cache_path = "cache"
optimizer = true
optimizer_runs = 20_000

remappings = [
    # note: map to package level only, required for pnp-berry to work with foundry
    # ok - solidity-stringutils/=node_modules/solidity-stringutils/
    # not ok - solidity-stringutils/=node_modules/solidity-stringutils/src/
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/src/ds-test/src/',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/src/forge-std/src/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    'solidity-bytes-utils/=node_modules/solidity-bytes-utils/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    '@layerzerolabs/lz-evm-oapp-v2/=node_modules/@layerzerolabs/lz-evm-oapp-v2/',
    '@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/',
    '@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/',
    '@layerzerolabs/lz-evm-v1-0.7/=node_modules/@layerzerolabs/lz-evm-v1-0.7/',
    '@layerzerolabs/test-devtools-evm-foundry/=node_modules/@layerzerolabs/test-devtools-evm-foundry/',
]

[fuzz]
runs = 1000
