[package]
# name = "oft"
name = "MyOFT"
version = "0.0.0"
authors = []

[addresses]
MyOFT = "_"
# oft = "_"
# oft_common = "_"
# router_node_0 = "_"
# simple_msglib = "_"
# blocked_msglib = "_"
# uln_302 = "_"
# router_node_1 = "_"
# endpoint_v2_common = "_"
# endpoint_v2 = "_"
# layerzero_admin = "_"
# layerzero_treasury_admin = "_"
# msglib_types = "_"
# treasury = "_"
# worker_peripherals = "_"
# price_feed_router_0 = "_"
# price_feed_router_1 = "_"
# price_feed_module_0 = "_"
# worker_common = "_"
# executor_fee_lib_router_0 = "_"
# executor_fee_lib_router_1 = "_"
# dvn_fee_lib_router_0 = "_"
# dvn_fee_lib_router_1 = "_"
# executor_fee_lib_0 = "_"
# dvn_fee_lib_0 = "_"
# dvn = "_"
# native_token_metadata_address = "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"
# For Initia: "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"

[dev-addresses]
# oft = "0x302814823"
# oft_common = "0x30281482332"
# router_node_0 = "0x9001"
# simple_msglib = "0x9002"
# blocked_msglib = "0x9003"
# uln_302 = "0x9005"
# router_node_1 = "0x9007"
# endpoint_v2_common = "0x9098"
# endpoint_v2 = "0x12345678"
# layerzero_admin = "0x18943124"
# layerzero_treasury_admin = "0x1894312499"
# msglib_types = "0x5211234"
# treasury = "0x123432432"
# worker_peripherals = "0x3000"
# price_feed_router_0 = "0x65DD71A"
# price_feed_router_1 = "0x65DD71AB"
# price_feed_module_0 = "0x65DD71"
# worker_common = "0x3999"
# executor_fee_lib_router_0 = "0x30001"
# executor_fee_lib_router_1 = "0x30002"
# dvn_fee_lib_router_0 = "0x30001a"
# dvn_fee_lib_router_1 = "0x30002a"
# executor_fee_lib_0 = "0x2153423"
# dvn_fee_lib_0 = "0x2153423a"
# dvn = "0x234234"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/movevm.git"
rev = "b810effbdb28e330c5d29eaf25e7b05299c418e1"
subdir = "precompile/modules/initia_stdlib"

[dependencies]
# endpoint_v2_common = { local = "../../endpoint_v2_common" }
# endpoint_v2 = { local = "../../endpoint_v2" }
# oft_common = { local = "../oft_common" }

[dev-dependencies]
# simple_msglib = { local = "../../msglib/libs/simple_msglib" }