packages:
  - "examples/*"
  - "packages/*"
  - "tests/*"
  - "!tests/devtools-cli-test"
  - "!tests/devtools-evm-hardhat-test"
  - "!tests/devtools-evm-test"
  - "!tests/export-deployments-test"
  - "!tests/test-evm-node"
  - "!tests/test-setup-devtools-evm-hardhat"
  - "!tests/ua-devtools-evm-hardhat-test"
  - "!tests/ua-devtools-evm-hardhat-v1-test"
