import './sendOFT'
import './simple-workers-mock/commit'
import './simple-workers-mock/verify'
import './simple-workers-mock/lzReceive'
import './simple-workers-mock/process-receive'
import './simple-workers-mock/setReceiveConfig'
import './simple-workers-mock/setSendConfig'
