#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
#
#           Reusable services for docker compose
#
#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
version: "3.9"

services:
  # Service that can build this package
  package:
    build:
      args:
        PACKAGE: "@layerzerolabs/ua-utils-evm-hardhat-test"
    extends:
      file: ../../docker-compose.templates.yaml
      service: project
    working_dir: /app/packages/ua-utils-evm-hardhat-test
    volumes:
      - ./:/app/packages/ua-utils-evm-hardhat-test

  # Hardhat node started on port 8545
  node:
    extends:
      service: package
    expose:
      - 8545
    command: ["npx", "hardhat", "node", "--hostname", "0.0.0.0", "--no-deploy"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8545/"]
