[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "6Vju5NhRNcBkftQMjpNtynbuyoURF9bqGm1m5NLJjc2P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nazreen.mohamad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
