[workspace]
members = [
    "programs/*",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 20

[profile.release.build-override]
opt-level = 0
incremental = false
codegen-units = 20