#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
#
#           Docker compose for running E2E tests
#
#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
version: "3.9"

services:
    # ~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~
    #
    #        Network nodes, one for every hardhat network
    #
    # .oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.
    network-vengaboys:
        extends:
            file: docker-compose.templates.yaml
            service: node

    network-britney:
        extends:
            file: docker-compose.templates.yaml
            service: node

    # ~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~
    #
    #        Bootstrap script that deploys all the networks
    #
    # .oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.
    bootstrap:
        extends:
            file: docker-compose.templates.yaml
            service: package
        depends_on:
            network-vengaboys:
                condition: service_healthy
            network-britney:
                condition: service_healthy
        # Can't say I love the fact that the deploy scripts are inlined here
        # but at least it's all in this file that bootstraps the whole environment
        #
        # The "&" at the end of the lines and "wait" work together to execute the deployments
        # in parallel and wait until they are all complete
        command:
            - /bin/bash
            - -c
            - |
                npx hardhat --network vengaboys deploy --reset &
                npx hardhat --network britney deploy --reset &
                wait

    # ~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~
    #
    #                       The actual tests
    #
    # .oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.
    tests:
        extends:
            file: docker-compose.templates.yaml
            service: package
        depends_on:
            bootstrap:
                condition: service_completed_successfully
        command: ["npx", "hardhat", "test"]
