[package]
name = "oft"
version = "1.0.0"
authors = []

[addresses]
oft = "_"
oft_admin = "_"
blocked_msglib = "_"
dvn = "_"
dvn_fee_lib_0 = "_"
dvn_fee_lib_router_0 = "_"
dvn_fee_lib_router_1 = "_"
endpoint_v2 = "_"
endpoint_v2_common = "_"
executor_fee_lib_0 = "_"
executor_fee_lib_router_0 = "_"
executor_fee_lib_router_1 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
msglib_types = "_"
oft_common = "_"
price_feed_module_0 = "_"
price_feed_router_0 = "_"
price_feed_router_1 = "_"
router_node_0 = "_"
router_node_1 = "_"
simple_msglib = "_"
treasury = "_"
uln_302 = "_"
worker_common = "_"
worker_peripherals = "_"

[dev-addresses]
oft = "0x1000001"
oft_admin = "0x2000000"
blocked_msglib = "0x1000002"
dvn = "0x1000003"
dvn_fee_lib_0 = "0x1000004"
dvn_fee_lib_router_0 = "0x1000005"
dvn_fee_lib_router_1 = "0x1000006"
endpoint_v2 = "0x1000007"
endpoint_v2_common = "0x1000008"
executor_fee_lib_0 = "0x1000009"
executor_fee_lib_router_0 = "0x100000a"
executor_fee_lib_router_1 = "0x100000b"
layerzero_admin = "0x100000c"
layerzero_treasury_admin = "0x100000d"
msglib_types = "0x100000e"
oft_common = "0x100000f"
price_feed_module_0 = "0x1000010"
price_feed_router_0 = "0x1000011"
price_feed_router_1 = "0x1000012"
router_node_0 = "0x1000013"
router_node_1 = "0x1000014"
simple_msglib = "0x1000015"
treasury = "0x1000016"
uln_302 = "0x1000017"
worker_common = "0x1000018"
worker_peripherals = "0x1000019"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/move-natives.git"
rev = "77d5f3e140143bdaa41f850115b3035c134193e3"
subdir = "initia_stdlib"

[dependencies]
endpoint_v2_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/initia/contracts/endpoint_v2_common" }
endpoint_v2 = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/initia/contracts/endpoint_v2" }
oft_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/initia/contracts/oapps/oft_common" }

[dev-dependencies]
simple_msglib = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/initia/contracts/msglib/libs/simple_msglib" }
