[profile.default]
solc-version = '0.8.22'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache'
libs = ['node_modules', 'node_modules/@layerzerolabs/toolbox-foundry/lib', '../../node_modules']

remappings = [
    '@layerzerolabs/=node_modules/@layerzerolabs',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
