[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
composer = "2TUdVCMQsefMs28hTeMKAHTjgz8cdMbo7V5oEdrYSu7G"
oft = "BH2YoCQV4i7gagmJqhj6nBByroJJwAQHa76XKV921e9m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "./krak.json"

[scripts]
test = "npx jest test/anchor/"
