[profile.default]
solc = '0.8.22'
verbosity = 3
src = "contracts"
test = "test"
out = "artifacts"
cache_path = "cache"
optimizer = true
optimizer_runs = 200

remappings = [
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/src/ds-test/src/',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/src/forge-std/src/',
    '@openzeppelin=node_modules/@openzeppelin/',
    'solidity-bytes-utils/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/solidity-bytes-utils/',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
]

[fuzz]
runs = 1000
