name: Install project dependencies
description: Install everything we need to build this repo
runs:
  using: "composite"
  steps:
    # Install the dependencies and run the post-install scripts
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --offline
